### ISSUE TITLE
New version 1.5

### ISSUE THREAD

**Issue by kopsec** [bwack/Versa64Cart#10]
I have made small mods to V1.4 dessign, really don't know the exact differences with v1.4

- Added a SP3T slide swith for J6 (very usefull for mounting inside a cartridge case). Do not use switch and pin headers at same time, use only one.
- Removed all the vias near the edge connector, this allow the PCB to be manufactured using GOLD ENIG "gold fingers".
- Increased diameter on vias holes to 0.5mm to be compatible with PCBs manufacturers.
- Increased also some layers width.
[Versa64Cart_v1_5.zip](https://github.com/bwack/Versa64Cart/files/3803488/Versa64Cart_v1_5.zip)
![P1010643](https://user-images.githubusercontent.com/10632883/68113701-ada11080-fef4-11e9-8b12-ba8c44b65402.JPG)
![P1010644](https://user-images.githubusercontent.com/10632883/68113749-bc87c300-fef4-11e9-81f4-478db2e3d39e.JPG)

**Comment by bwack** [comment]
Hi it nice to see people take an interest in this design. I'm not having time and energy to work on a new version now. Also because the design moved from KiCad to Eagle by Sven I don't have the tools to verify. Sorry.

**Comment by kopsec** [comment]
OK. I don't know how to work with GitHub, so I put it here, just to share it with people.
Just say that is tested and working. Cheers!
