### ISSUE TITLE
lack of information regarding .bin files merging

### ISSUE THREAD

**Issue by vidmo91** [bwack/Versa64Cart#11]
Hi,
it's not a big deal, but adding that info to the manual would help others. I waste some time using a few bad methods before finding good one.

Simplest working method in Windows:
1. open cmd in folder containing bin files,
2. use command form merging binary files files into new one:
`copy /b file_1.bin + file_2.bin + ... + file_n.bin output_file.bin`
eg. 
`copy /b DeadTest.bin + jupiterl.bin + SomeGame.bin combined.bin`
or
`copy /b DeadtTest.bin + jupiterl.bin combined.bin`

This for sure won't work: copy-paste in Hex-editor plugin of Notepad++

**Comment by bwack** [comment]
@svenpetersen1965 Any suggestions ?

**Comment by svenpetersen1965** [comment]
I can integrate it into the manual. It will not work, if a files has other than exactly 8k or 16k content, though.

**Comment by bwack** [comment]
Right, the problem you mention Sven is a special case for mixed 8k and 16k game images. What you can do then is a simple trick and copy the same 8k binary twice. In that way you are making only 16k slots. Example with one 8k game and 16k game on a 32k eeprom:

`copy /b first8kgame.bin + first8kgame.bin + second16kgame.bin epromimage.bin`

but when I think of it you don't have to copy the first game twice if you have two 8k games :D (but there has to be two 8k games next to eachother, the same or not)

Maybe also an example in the docs would be nice, and titles like "Example I - deadtest", etc.. If you like I can try import the msword doc into google docs format and we can work on it together. I'd like to fix some small mistakes. Google docs can save to pdf also.

**Comment by svenpetersen1965** [comment]
I have changed the Module description. Please find it on the google drive.

**Comment by bwack** [comment]
Thanks for updating, Sven. Closing this issue.
