### ISSUE TITLE
Suggestion: Replace SW1 and solder blobs by pin/jumper

### ISSUE THREAD

**Issue by pablocastine** [bwack/Versa64Cart#15]
Just wanted to know your opinion about replacing the DIP switch at SW1 and the solder blobs at GAME/EXROM/A13/A14/A15 by standard 2.54mm pitch pins as found in ROMH/ROML in order to a) some sellers might not have that specific 5-bit DIP switch in stock and b) 100% solder-less configuration using standard jumpers.

Thanks.

**Comment by bwack** [comment]
Thats not a bad idea. The 5pin dip atleast could have an extra row of 5 gnd pins to accept 2.54 pin pitch header. Lets ask @svenpetersen1965  :)

**Comment by svenpetersen1965** [comment]
I think, the Dip-switch can be replaced with a combination footprint of a jumper and the dip switch. I was thinking of that already some days ago. I would prefer to keep the solder bridges as is, because they are of good use.

**Comment by bwack** [comment]
Thanks Sven! I have updated the repository and releases.

**Comment by pablocastine** [comment]
Great work guys!
