### ISSUE TITLE
Typo in 16k Game documentation for 1.4 and 1.5

### ISSUE THREAD

**Issue by bagofarms** [bwack/Versa64Cart#16]
On page 7 of the 1.4 and 1.5 documentation, in the section titled "4.4. Example III", I believe there is a typo on the first row of the table.  The neutron.crt file reports `exrom: 0 game: 0 (16k Game)`, and I think `0 (=LOK)` is supposed to be `0 (=LOW)`.  Also, I think the Setting column for !GAME is supposed to be `SW1-1 = ON` instead.  I tested this with doccosmos.crt, which reports the same information as the neutron.crt example in the documentation, and having SW1-1 set to ON worked perfectly.

(P.S. Great work on this pcb!  It's so compact and well documented.  I went from not knowing anything about C64 cartridges to building my own cart and flashing the ROM chips within a couple of hours!)

**Comment by bwack** [comment]
Sorry for the late reply. I'll have to ask  @svenpetersen1965  for help on this one :)

**Comment by bwack** [comment]
You are right ! :) It should say LOW and ON :) Thanks for help !

**Comment by bwack** [comment]
Thanks for the tip and also thanks for help by  @svenpetersen1965  :)

**Comment by bagofarms** [comment]
Glad I could help!
