### ISSUE TITLE
Question: why the switch from KiCad to Eagle ?

### ISSUE THREAD

**Issue by UffeJakobsen** [bwack/Versa64Cart#17]
Question: why the switch from KiCad to Eagle ?

It would seem more logical to have an open project like this supported by an open program as KiCad - than a proprietary program as Eagle

**Comment by bwack** [comment]
Hi. I agree regarding open design and tools. The eagle boards are drawn by Sven. It adds some minor changes, but they are not anything you will need or mis in V1.1 KiCad version.
https://github.com/bwack/Versa64Cart/releases/tag/V1.1

**Comment by UffeJakobsen** [comment]
Thanks for your answer
Well - I'm interested in some of the changes up to and including version 1.5
So I guess that I'll have to check if the new KiCad Eagle import is as good as they say :-)

**Comment by bwack** [comment]
I tried KiCad Eagle import in KiCad 5.1.4, and I'm impressed. :)

![Screenshot from 2020-10-17 20-32-53](https://user-images.githubusercontent.com/11380333/96350885-35593e00-10b8-11eb-986b-21800ad582a5.png)

**Comment by UffeJakobsen** [comment]
Yes, exactly my point - the KiCad 5.x release series has improved a lot of things.
Actually I've not yet tried the Eagle import - but guess that your picture is the result of an Eagle import into KiCad  ? :-)

**Comment by bwack** [comment]
Yes. I tried another project too now, and it also went well. It was a hotplate "soldering iron" project :) https://github.com/makermoekoe/Hotplate-Soldering-Iron

**Comment by UffeJakobsen** [comment]
Great news - thanks :+1:
