### ISSUE TITLE
28C64 EEPROM?

### ISSUE THREAD

**Issue by oXL0C0Xo** [bwack/Versa64Cart#19]
I'm curious if there is a way to use a 28C64 EEPROM in this instead of a 27C64, as I have a ton of them. I have tried, but I just get a black screen. It looked like the 28C64 was pin compatible, so I was thinking this is strange. Anyways, thank you for the project!

**Comment by UffeJakobsen** [comment]
Hmm, they should work... what brand and speed grade are the 28C64's ?
If you could post the full text from the full text found on the top of the IC - or a photo

**Comment by oXL0C0Xo** [comment]
It's at Microchip 28C64AF-15/P
![s-l1600](https://github.com/bwack/Versa64Cart/assets/16486317/a04581f7-7cd1-47d4-b00b-5e0641d97bfa)

**Comment by UffeJakobsen** [comment]
Ok - just to be sure - A14 and A15 are left open ? or ?

**Comment by oXL0C0Xo** [comment]
Ok, so this is how I currently have it soldered. On page 9 of the documentation, it says those three should be open. So I didnt solder them high or low.
![EF6F2863-620F-4555-AD38-6DE50E037234](https://github.com/bwack/Versa64Cart/assets/16486317/b08c59a6-386e-42fc-bb4e-d0af0a07f43e)

**Comment by UffeJakobsen** [comment]
Good hat you posted that photo - I assumed (wrong) that you had populated your PCB with resistors.

You should re-read section 2.4 "Solder Bridges"

I think that you need to solder JP9 and JP11 - but please re-read section 2.4 and make up your own mind.

As stated in the section 2.4 - please ensure that any of the solderjoint-pairs  JP8/JP9, JP10/JP11 and JP12/JP14 are *NEVER* both closed at the same time - that will short-circuit V5 to GND  :-S

**Comment by oXL0C0Xo** [comment]
Still black screen. I added jumpers and the resistors to see if it would make any difference. Here’s how it’s jumpers now
![D9475AE8-3114-4125-BA9C-A0E21E53E85C](https://github.com/bwack/Versa64Cart/assets/16486317/797d2ebf-2b3b-48ea-abd3-5a3ca86e6e7b) 

just trying to make a dead test cartridge

**Comment by UffeJakobsen** [comment]
As far as I can see - the jumper config on the last photo is illegal.

For "Dead Test Cartrigde" (Ultimax mode): 
EXROM=H
GAME=L
ROML=no jumper
ROMH=jumper set

For "Diagnostics Cartridge" ($8000 - 8k):
EXROM=L
GAME=H
ROML=jumper  set
ROMH=no jumper

**Comment by oXL0C0Xo** [comment]
I finally did end up getting this working using the following configuration. Thank you for all of your help 👍 
![1165C1CA-3BE5-46EA-8225-F97B843D7366](https://github.com/bwack/Versa64Cart/assets/16486317/282ce60c-e0ca-4f77-b135-9150d09189ad)

**Comment by UffeJakobsen** [comment]
That is good to hear :+1:
