### ISSUE TITLE
Bomberland 64k

### ISSUE THREAD

**Issue by rmueller83** [bwack/Versa64Cart#2]
Hi,

[Bomberland](https://rgcddev.itch.io/bomberland) is not available for order any more, but the 64k crt is freely downloadable at the bottom of the linked webpage. It should fit in a 27C512 but the Versa64Cart manual only lists 8k and 16k configurations. Would this work with Versa64Cart?

```
cartconv -f bomberland.crt
CRT Version: 1.0
Name: VICE CART
Hardware ID: 19 (Magic Desk)
Mode: exrom: 0 game: 1 (8k Game)

offset  sig  type  bank start size  chunklen
$000040 CHIP ROM   #000 $8000 $2000 $2010
$002050 CHIP ROM   #001 $8000 $2000 $2010
$004060 CHIP ROM   #002 $8000 $2000 $2010
$006070 CHIP ROM   #003 $8000 $2000 $2010
$008080 CHIP ROM   #004 $8000 $2000 $2010
$00a090 CHIP ROM   #005 $8000 $2000 $2010
$00c0a0 CHIP ROM   #006 $8000 $2000 $2010
$00e0b0 CHIP ROM   #007 $8000 $2000 $2010

total banks: 8 size: $010000
```

**Comment by bwack** [comment]
Hi. No. I would guess it would need more digital logic circuits to switch between the eight banks.

**Comment by tomse** [comment]
Sorry for posting to an older thread, but Bomberland is indeed available still
http://rgcd.bigcartel.com/product/bomberland-commodore-64
