### ISSUE TITLE
Dead Test Cart on 27C256

### ISSUE THREAD

**Issue by sajattack** [bwack/Versa64Cart#4]
I couldn't find any 27C64's like the guide recommends for a Dead Test Cart so I programmed it into the lower 8K of a 27C256 and zeroed the rest. I followed the guide, jumping JP3, JP4, and JP6. It doesn't seem to be working. Any ideas why? Are there any solutions that don't involve reprogramming the chip? It's already soldered in (unsocketed) and I don't really want to have to desolder it. Hope you can help. If there's a better place for support requests please let me know.

**Comment by bwack** [comment]
If you are in doubt, check the schematic, and find the pins for A15 and A14. Use a multimeter to check that the voltage is low on those pins. If they are low then the C64 should reach the lower region of the 27C256. I'll add this to the documentation, thanks !

**Comment by bwack** [comment]
Solder wires on SW1 to pull A15 and A14 to ground. I'm assuming you don't have SW1 dip switch on this board.

**Comment by bwack** [comment]
and A13. Sorry too late. My head is not working.

**Comment by bwack** [comment]
A15 has only an effect on 27C512 :) so it is A13 and A14 then.

**Comment by sajattack** [comment]
Thanks. Got it working.

**Comment by sajattack** [comment]
@bwack Actually, it works on every cart I made other than the Dead Test. Even an ultimax Jupiter Lander works, but dead test is black screening. Any ideas? Also, would you consider adding solder jumpers for A13, A14, and A15 in a future board revision?

Edit: got it working, loose connection.

**Comment by bwack** [comment]
Great :) I was surprised that the Dead Test takes 20seconds to show anything on the screen. The first time I thought there was something wrong with the cart.
