### ISSUE TITLE
sharewareplus and tfw8bit stumpy cart enclosures does not fit

### ISSUE THREAD

**Issue by bwack** [bwack/Versa64Cart#8]
Issue regarding Versa64cart v1.1 and v1.2

# sharewareplus cart enclosure hits the diode
The sharewareplus cartridge enclosure beam near the pcb edge fingers rest on top of the diodes.
http://sharewareplus.blogspot.com/

# tfw8bit stumpy 1mm narrower
The stumpy cart dimensions is different to Commodore. It is only a millimeter or so it should be easy to modify the pcb to fit all the carts out there.
https://www.thefuturewas8bit.com/shop/commodore/c64romcart.html
![2019-05-30 14_30_25-Commodore C64 ROM Cartridge Case](https://user-images.githubusercontent.com/11380333/58633146-e73b7300-82e7-11e9-8270-5a2053d5bf39.png)

# retro innovations enclosure: jumpers hits roof
Currently, I've only tested the cartridge with cartriges from retro innovation. The jumpers hit the top enclosure wall. Might aswell be a problem in other carts
http://store.go4retro.com/categories/Commodore/Hardware/

**Comment by bwack** [comment]
@svenpetersen1965 Regarding sharewareplus and info from Antella on twitter, we know that the lip hits the diode in the v1.1 cartridge. As you can see it is not much.
![sharewareplus-cart-with-versacart](https://user-images.githubusercontent.com/11380333/58633598-3930c880-82e9-11e9-8c1c-48fd92048d66.png)

Note that in v1.2 the diodes are even further down. Here you can exactly how far the diodes are from the mounting hole center and down vertically to the diode holes.. (kicad v1.1). You can also see i have restrictions zones to fit with the retro innovations carts. Moving the diodes up may hit the studs on the sides. The blue outline is importet from mechanical drawing from simple64cart which is eagle btw. The eagle files are here. You could export just the mechanical layer and import that like i did: https://github.com/go4retro/Simple64Cart
![diodes](https://user-images.githubusercontent.com/11380333/58632578-3e404880-82e6-11e9-9bb1-000554734f40.png)
 
The sharewareplus cart hits the lowest hole, or I assume (Antella didn't say which)

**Comment by svenpetersen1965** [comment]
I have fixed the problem with the diodes being too far south. From v1.1 to v1.2 they moved south about 1mm. I have now moved them north about 5mm, they are aproximately flush with the IC socket. 

![versa_v1_3](https://user-images.githubusercontent.com/28980471/58639716-e01c6100-82f7-11e9-9d68-a9f70f91033f.png)

I have compared the width of 58mm woth all different cartridges I had. Dela DOS: 58.0mm, REX 9628: 58.0mm, FCIII+: 58.0mm, Simple64Cart57.8mm, Handic Forth 64: 58.0mm, Ultimate II+: 57.4mm. Right now, the Versa64Cart moves 0.8mm from one side to the other, after reducing width by 1mm, that would be 1.8mm. The pitch is 2.54mm. For my taste, it would be too much and we might get even shortcuts between the neigboring contacts. We should not do that.

**Comment by bwack** [comment]
Ok thanks a lot! for reference, the stumpy pcb is 57mm. I agree regarding not narrowing the board.

**Comment by bwack** [comment]
second problem is now that the diodes might hit the resting stands on the left. (and also on the right of the board, but that is the other issue).

**Comment by svenpetersen1965** [comment]
Moved the diodes east by 3.463mm. 
![versa_v1_3](https://user-images.githubusercontent.com/28980471/58641083-ccbec500-82fa-11e9-8f67-8012507f7500.png)
Anything else, that needs to be changed?

**Comment by bwack** [comment]
Awesome! Yesh, also https://github.com/bwack/Versa64Cart/issues/9 is a problem :)
