### ISSUE TITLE
v1.2 IC1 too close to right-edge

### ISSUE THREAD

**Issue by bwack** [bwack/Versa64Cart#9]
IC1 is too close to the right edge and hits resting-post on original cart and retro innovations cart. 
![DSC02594](https://user-images.githubusercontent.com/11380333/58636243-2241a480-82f0-11e9-9639-3ff31aa30d5a.jpg)
![DSC02596](https://user-images.githubusercontent.com/11380333/58636781-5c5f7600-82f1-11e9-97fc-7078633e2740.jpg)

retroinnovation cart. similar:
![DSC02597](https://user-images.githubusercontent.com/11380333/58636672-215d4280-82f1-11e9-8ae0-f47aad5d5a40.jpg)

This was a problem in Simple64cart too.
![DSC02595](https://user-images.githubusercontent.com/11380333/58636006-9a5b9a80-82ef-11e9-8b13-c152572ad307.jpg)

Versa64Cart v1.1 has the ic1 (U1 v1.1) about 1mm further to the left.

**Comment by svenpetersen1965** [comment]
![versa_v1_3](https://user-images.githubusercontent.com/28980471/58642691-22e13780-82fe-11e9-9cba-e579d0991e3e.png)
So now the IC and C1 are moved west by 1.6mm. Ok?

**Comment by bwack** [comment]
Perfect ! That should do the trick!

**Comment by svenpetersen1965** [comment]
So I generate the Gerbers :-) Maybe first optimize the traces a bit. And hey, the parcel arrived... that made my day :-)

**Comment by bwack** [comment]
Thanks. I'll order pcb's tonight myself of the new v1.3. Thanks alot for the boards in the parsel and Tee ! There will be future videos of a couple of these boards :)

**Comment by svenpetersen1965** [comment]
<3
